name = "r2-dir-list"
main = "src/index.ts"
compatibility_date = "2023-03-01"

workers_dev = false
routes = [
    { pattern = "dl.vikunja.io/*", zone_name = "vikunja.io" }
]

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/r2/api/workers/workers-api-usage/
r2_buckets  = [
    { binding = "BUCKET_vikunja", bucket_name = "vikunja"}
]

[observability]
# https://developers.cloudflare.com/workers/observability/logs/workers-logs/
enabled = true
head_sampling_rate = 1 # optional. default = 1.

